server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: ColorBites_be
  data:
    mongodb:
      uri: mongodb+srv://namdpse180259:SAQuea6TTmx7qiqk@cluster0.xssff0p.mongodb.net/colorbites_db?retryWrites=true&w=majority&appName=Cluster0
  main:
    banner-mode: off
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: warn
    org.springframework.data.mongodb: DEBUG
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api

