server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: ColorBites_be
  data:
    mongodb:
      uri: mongodb://localhost:27017/color_bites_db
      database: color_bites_db
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    root: warn
    org.springframework.data.mongodb: DEBUG
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api

# PayOS Configuration
payos:
  client-id: 8ec4087f-72a7-4f2b-a346-c5d7003f996f
  api-key: 1b5b8aec-6bc8-411e-b52a-a869b25441c5
  checksum-key: 204f6bfcbaa9269db6d170407b00d35a7276e28c17ad411783898d2519b630c0
  api-url: https://api-merchant.payos.vn
  return-url: http://localhost:8080/api/payment/payos/return
  cancel-url: http://localhost:8080/api/payment/payos/cancel
