name: Build and Deploy to Azure App Service

on:
  push:
    branches: [ develop, main ]  # Deploy khi push vào develop hoặc main
  workflow_dispatch:  # Cho phép chạy thủ công

env:
  AZURE_WEBAPP_NAME: mumii-be  # Tên App Service của bạn
  JAVA_VERSION: '21'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B -DskipTests clean package

    - name: Prepare deployment artifact
      run: |
        mkdir -p release
        cp target/*.jar release/app.jar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: java-app
        path: release/app.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: java-app
        path: .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: app.jar
