jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x ./mvnw

      # Optional: uncomment if you want to run tests
      # - name: Run tests
      #   run: ./mvnw test

      - name: Build application
        run: ./mvnw clean package -DskipTests

      - name: Verify JAR file
        run: |
          if [ ! -f target/ColorBites_be-0.0.1-SNAPSHOT.jar ]; then
            echo "Build failed - JAR file not found"
            exit 1
          fi
          echo "Build successful - JAR file created"

      - name: Upload JAR as GitHub Artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: ColorBites-be-jar
          path: target/ColorBites_be-0.0.1-SNAPSHOT.jar
