name: Publish OpenAPI to SwaggerHub

on:
  push:
    branches: [main, develop]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      API_NAME: mumii
      OWNER: ${{ secrets.SWAGGERHUB_OWNER }}
      SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Install swaggerhub-cli
        run: |
          npm install -g swaggerhub-cli
          swaggerhub --version

      - name: Push OpenAPI spec
        run: |
          swaggerhub api:create "${OWNER}/${API_NAME}/${VERSION}" \
            -f openapi.json || \
          swaggerhub api:update "${OWNER}/${API_NAME}/${VERSION}" \
            -f openapi.json


