name: Publish OpenAPI to SwaggerHub

on:
  push:
    branches: [main, develop]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      APP_DIR: .
      APP_PORT: 8080
      API_NAME: mumii
      OWNER: ${{ secrets.SWAGGERHUB_OWNER }}            # ví dụ: Namtechie (đúng y tên org)
      SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}  # **Organization API Key**

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build app (skip tests)
        working-directory: ${{ env.APP_DIR }}
        run: ./mvnw -q -DskipTests package || mvn -q -DskipTests package

      - name: Run app and wait for /v3/api-docs
        working-directory: ${{ env.APP_DIR }}
        run: |
          nohup java -jar $(ls target/*-SNAPSHOT.jar 2>/dev/null || ls target/*.jar | head -n1) --server.port=${APP_PORT} > app.log 2>&1 &
          echo $! > app.pid
          for i in {1..40}; do
            if curl -fsS "http://localhost:${APP_PORT}/v3/api-docs" -o openapi.json; then
              break
            fi
            sleep 3
          done
          test -s openapi.json || (echo 'Failed to fetch /v3/api-docs' && tail -n 120 app.log || true && exit 1)

      - name: Validate spec and extract version
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          jq -e '.openapi and .info.version' openapi.json > /dev/null
          echo "VERSION=$(jq -r '.info.version' openapi.json)" >> $GITHUB_ENV

      - name: Stop app
        if: always()
        working-directory: ${{ env.APP_DIR }}
        run: |
          if [ -f app.pid ]; then kill -9 $(cat app.pid) || true; fi
          tail -n 120 app.log || true

      - name: Set visibility by branch
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "VISIBILITY=public" >> $GITHUB_ENV
          else
            echo "VISIBILITY=private" >> $GITHUB_ENV
          fi

      - name: Install swaggerhub-cli
        run: |
          npm install -g swaggerhub-cli
          swaggerhub --version

      # Diagnose: xem OWNER có dư khoảng trắng / sai tên không
      - name: Debug OWNER and try listing org
        run: |
          echo "OWNER=>>${OWNER}<<"
          echo "len=$(echo -n "${OWNER}" | wc -c)"
          # đúng lệnh: apis:list
          swaggerhub apis:list "${OWNER}" --limit 1 || (echo "Access to OWNER failed. Check Org API key & OWNER." && exit 1)


      - name: Create or Update on SwaggerHub
        run: |
          echo "Publishing ${OWNER}/${API_NAME}/${VERSION} (visibility=${VISIBILITY})"
          swaggerhub api:create "${OWNER}/${API_NAME}/${VERSION}" -f openapi.json --visibility="${VISIBILITY}" || \
          swaggerhub api:update "${OWNER}/${API_NAME}/${VERSION}" -f openapi.json --visibility="${VISIBILITY}"

      - name: Publish version (main only)
        if: github.ref == 'refs/heads/main'
        run: swaggerhub api:publish "${OWNER}/${API_NAME}/${VERSION}"
        
      - name: Dry-run: try to create and show full error
        run: |
          set -x
          swaggerhub api:create "${OWNER}/${API_NAME}/${VERSION}" -f openapi.json --visibility="${VISIBILITY}" --debug || true

